version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: boringfinance-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
      - MONGO_INITDB_DATABASE=boringfinance

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - DB_URL=mongodb://admin:secretpassword@mongodb:27017/boringfinance?authSource=admin

volumes:
  mongodb_data: